# Generated by Django 3.2.6 on 2021-12-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_auto_20211228_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='position_id',
            new_name='position',
        ),
    ]
